### ISSUE TITLE
multi_tap arbitrary distance support

### ISSUE THREAD

**Issue by domportera** [Federico-Ciuffardi/GodotTouchInputManager#25]
Is there currently a way to have multi tap events fire regardless of finger distance? I tried editing some `InputManager` constants to no avail.

PS: thanks a ton for making this! if you're at all interested I can create a pull request for C# compatibility

**Comment by Federico-Ciuffardi** [comment]
Yes, setting [`FINGER_SIZE`](https://github.com/Federico-Ciuffardi/GodotTouchInputManager#configuration) to infinity (or a large enough number) should do that.

I don't use C#, but feel free to create a PR for C# compatibility if you want! You would be the main maintainer of that C# support. Also see @tuto193 at https://gitlab.com/tuto193/godot-sharp-touch-input-manager as this is probably related.

**Comment by domportera** [comment]
> Yes, setting [`FINGER_SIZE`](https://github.com/Federico-Ciuffardi/GodotTouchInputManager#configuration) to infinity (or a large enough number) should do that. Please let me know if it worked so I can close this.
> 
> I don't use C#, but feel free to create a PR for C# compatibility if you want! You would be the main maintainer of that C# support. Also see @tuto193 work at https://gitlab.com/tuto193/godot-sharp-touch-input-manager as this is probably related.

that did it, thanks! I can close this for you.

Wow I wish I knew that existed before I went about struggling with how C#/gd interop works 😅 but I'm better for knowing it.
I just ended up piggy-backing off your GD script, which I think is for the best - that way there's a single source of truth. Once I feel like it's ready for prime-time, I'll make a PR!
