### ISSUE TITLE
it's not working in godot 4 beta

### ISSUE THREAD

**Issue by pooyapower** [Federico-Ciuffardi/GodotTouchInputManager#26]
hi thanks for your project.
i downloaded the files and also demo files.
but it's not working.
![Untitled](https://user-images.githubusercontent.com/36620298/214700286-2aacfc8a-d448-40c3-9a78-f76f7ed76d69.png)

**Comment by Federico-Ciuffardi** [comment]
Hi! Efforts to support Godot 4 started in #22 feel free to work on it.

I'll close this issue so we only have one "Godot 4 Support" issue (#22).
