### ISSUE TITLE
Swipe, tap input not received when use get_tree().paused on Mobile device

### ISSUE THREAD

**Issue by dqdthanhthanh** [Federico-Ciuffardi/GodotTouchInputManager#29]
Swipe and tap input not received when use get_tree().paused on Mobile device.
Godot version: 4.1 rc, 4.0 stable.
Device testing: Android 11, iPhone 11.

Steps to reproduce:
- Use get_tree().paused = true then get_tree().paused = false for UI show, hide (pause mode).
- Swipe and tap input not received anymore. (Ex: InputEventSingleScreenSwipe and InputEventSingleScreenTap)
- Other inputs such as drag, touch, pinch are still received normally.

**Comment by Federico-Ciuffardi** [comment]
I think this could be caused by the `InputManger` also being paused when `get_tree().paused == true` , if you can, check and let me know if #31 solves your problem.

**Comment by dqdthanhthanh** [comment]
I didn't think of it. Seems to work, I just tried on godot 4.1 stable still no problem with input. Thanks
