### ISSUE TITLE
Debug mode prints empty messages on console

### ISSUE THREAD

**Issue by btzr-io** [Federico-Ciuffardi/GodotTouchInputManager#40]
I'm guessing this is a typo ?

https://github.com/Federico-Ciuffardi/GodotTouchInputManager/blob/89efa65dc9a04d29e91e80f00191f04889603c3f/InputManager.gd#L287

Replacing as_text for as_string shows the debug messages correctly:
>  if DEBUG: print(val.as_string())

**Comment by Federico-Ciuffardi** [comment]
Yes! It seems we forgot to change this one when transitioning to Godot 4.

 Could you please make a PR?
